#!/bin/sh

# Determine the version string to build into a binary.
# When building in the git repository, we can use the output 
# of "git describe" which gives an unequivocal answer.
#
# Failing that, we use the contents of the VERSION file
# which has a set of references substituted into it by git.
# If we can find one which matches $v[0-9].* then we assume it's
# a version-number tag, else we just use the whole string.

# we're called with pwd == src
cd ..

if [ -d .git ]; then
     git describe
else
     vers=`cat VERSION | sed 's/[(), ]/\n/ g' | grep -m 1 $v[0-9]`

     if [ $? -eq 0 ]; then
         echo ${vers#v}
     else
         cat VERSION
     fi
fi

exit 0

